name: Deploy to Heroku

# Run on pushes and PRs to the main branch
on:
  push:
    branches:
      - [main]

# Your workflows job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Build, Push and release docker container to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_file_directory: ./
          docker_file_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web